config/routes.rb
Rails.application.routes.draw do
  resources :hobbies
  resources :comments
  resources :users
  resources :language_lists
  resources :users
  resources :language_lists
  resources :comments
  resources :comments

end

app/models/language_list.rb
class LanguageList < ActiveRecord::Base
	has_and_belongs_to_many :user
end

app/controllers/language_lists_controller.rb
class LanguageListsController < ApplicationController
  before_action :set_language_list, only: [:show, :edit, :update, :destroy]

  # GET /language_lists
  # GET /language_lists.json
  def index
    @language_lists = LanguageList.all
  end

  # GET /language_lists/1
  # GET /language_lists/1.json
  def show
  end

  # GET /language_lists/new
  def new
    @language_list = LanguageList.new
  end

  # GET /language_lists/1/edit
  def edit
  end

  # POST /language_lists
  # POST /language_lists.json
  def create
    @language_list = LanguageList.new(language_list_params)

    respond_to do |format|
      if @language_list.save
        format.html { redirect_to @language_list, notice: 'Language list was successfully created.' }
        format.json { render :show, status: :created, location: @language_list }
      else
        format.html { render :new }
        format.json { render json: @language_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /language_lists/1
  # PATCH/PUT /language_lists/1.json
  def update
    respond_to do |format|
      if @language_list.update(language_list_params)
        format.html { redirect_to @language_list, notice: 'Language list was successfully updated.' }
        format.json { render :show, status: :ok, location: @language_list }
      else
        format.html { render :edit }
        format.json { render json: @language_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /language_lists/1
  # DELETE /language_lists/1.json
  def destroy
    @language_list.destroy
    respond_to do |format|
      format.html { redirect_to language_lists_url, notice: 'Language list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language_list
      @language_list = LanguageList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_list_params
      params.require(:language_list).permit(:code, :name, :flag, :mothertongue, :learnedLanguage, :created_at, :updated_at)
    end
end

app/helpers/language_lists_helper.rb
module LanguageListsHelper
end

app/views/language_lists/_form.html.erb
<%= form_for(@language_list) do |f| %>
  <% if @language_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language_list.errors.count, "error") %> prohibited this language_list from being saved:</h2>

      <ul>
      <% @language_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :flag %><br>
    <%= f.text_field :flag %>
  </div>
  <div class="field">
    <%= f.label :mothertongue %><br>
    <%= f.check_box :mothertongue %>
  </div>
  <div class="field">
    <%= f.label :learnedLanguage %><br>
    <%= f.check_box :learnedLanguage %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.date_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.date_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/language_lists/edit.html.erb
<h1>Editing Language List</h1>

<%= render 'form' %>

<%= link_to 'Show', @language_list %> |
<%= link_to 'Back', language_lists_path %>

app/views/language_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Language Lists</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Flag</th>
      <th>Mothertongue</th>
      <th>Learnedlanguage</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @language_lists.each do |language_list| %>
      <tr>
        <td><%= language_list.code %></td>
        <td><%= language_list.name %></td>
        <td><%= language_list.flag %></td>
        <td><%= language_list.mothertongue %></td>
        <td><%= language_list.learnedLanguage %></td>
        <td><%= language_list.created_at %></td>
        <td><%= language_list.updated_at %></td>
        <td><%= link_to 'Show', language_list %></td>
        <td><%= link_to 'Edit', edit_language_list_path(language_list) %></td>
        <td><%= link_to 'Destroy', language_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language list', new_language_list_path %>

app/views/language_lists/new.html.erb
<h1>New Language List</h1>

<%= render 'form' %>

<%= link_to 'Back', language_lists_path %>

app/views/language_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @language_list.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @language_list.name %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @language_list.flag %>
</p>

<p>
  <strong>Mothertongue:</strong>
  <%= @language_list.mothertongue %>
</p>

<p>
  <strong>Learnedlanguage:</strong>
  <%= @language_list.learnedLanguage %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @language_list.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @language_list.updated_at %>
</p>

<%= link_to 'Edit', edit_language_list_path(@language_list) %> |
<%= link_to 'Back', language_lists_path %>