config/routes.rb
Rails.application.routes.draw do
  resources :hobbies
  resources :comments
  resources :users
  resources :language_lists
  resources :users
  resources :language_lists
  resources :comments
  resources :comments

end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
has_and_belongs_to_many :user
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]

  # GET /hobbies
  # GET /hobbies.json
  def index
    @hobbies = Hobby.where(parent_id: params[:parent_id])
  end

  # GET /hobbies/1
  # GET /hobbies/1.json
  def show
  end

  # GET /hobbies/new
  def new
    @hobby = Hobby.new
  end

  # GET /hobbies/1/edit
  def edit
  end

  # POST /hobbies
  # POST /hobbies.json
  def create
    @hobby = Hobby.new(hobby_params)

    respond_to do |format|
      if @hobby.save
        format.html { redirect_to @hobby, notice: 'Hobby was successfully created.' }
        format.json { render :show, status: :created, location: @hobby }
      else
        format.html { render :new }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hobbies/1
  # PATCH/PUT /hobbies/1.json
  def update
    respond_to do |format|
      if @hobby.update(hobby_params)
        format.html { redirect_to @hobby, notice: 'Hobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @hobby }
      else
        format.html { render :edit }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hobbies/1
  # DELETE /hobbies/1.json
  def destroy
    @hobby.destroy
    respond_to do |format|
      format.html { redirect_to hobbies_url, notice: 'Hobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hobby
      @hobby = Hobby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hobby_params
      params.require(:hobby).permit(:label, :weight)
    end
end

app/views/hobbies/_form.html.erb
<%= form_for(@hobby) do |f| %>
  <% if @hobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hobby.errors.count, "error") %> prohibited this hobby from being saved:</h2>

      <ul>
      <% @hobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hobbies/edit.html.erb
<h1>Editing Hobby</h1>

<%= render 'form' %>

<%= link_to 'Show', @hobby %> |
<%= link_to 'Back', hobbies_path %>

app/views/hobbies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hobbies</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hobbies.each do |hobby| %>
      <tr>
        <td><%= hobby.label %></td>
        <td><%= hobby.weight %></td>
        <td><%= link_to 'Show', hobby %></td>
        <td><%= link_to 'Edit', edit_hobby_path(hobby) %></td>
        <td><%= link_to 'Destroy', hobby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hobby', new_hobby_path %>

app/views/hobbies/new.html.erb
<h1>New Hobby</h1>

<%= render 'form' %>

<%= link_to 'Back', hobbies_path %>

app/views/hobbies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @hobby.label %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @hobby.weight %>
</p>

<%= link_to 'Edit', edit_hobby_path(@hobby) %> |
<%= link_to 'Back', hobbies_path %>